development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://chatte.herokuapp.com/faye"
  secret_token: "b2df52f36a7f1916d4e28c712841153fd71a4915f7ebef97786c42c9ee52607b"
  signature_expiration: 3600 # one hour
