development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"

production:
  host: "panga.redistogo.com"
  port: "9466"
  password: "c82bd6eb849dc7cc887ee03d0ca12414"
  database: "1"
  namespace: '/namespace'